app/forms.py
from wtforms import Form, TextField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms import validators
from wtforms.validators import InputRequired
 
class CityForm(Form):
  location = TextField(validators=[InputRequired()])
  submit = SubmitField("GO !")

app/__init__.py
from flask import Flask

def create_app():

    application = Flask(__name__,
                        static_url_path="",
                        static_folder="static")

    # Available environments are Production and Development
    ENV = "Production"

    application.config.from_object(f"config.{ENV}Config")
    application.config['VERSION'] = "1.6.1"

    from app.weather.routes import weather_blueprint
    from app.map.routes import map_blueprint
    from app.about.routes import about_blueprint
    from app.errors.routes import errors_blueprint

    application.register_blueprint(weather_blueprint)
    application.register_blueprint(map_blueprint, url_prefix="/map")
    application.register_blueprint(about_blueprint, url_prefix="/about")
    application.register_blueprint(errors_blueprint)

    return application

app/about/routes.py
from flask import Blueprint, render_template, request
from app.forms import CityForm

about_blueprint = Blueprint('about_blueprint',
                            __name__,
                            template_folder='templates')

@about_blueprint.route("/")
def about():
    city_form = CityForm(request.form)
    return render_template("about.html",
                           city_form=city_form)

@about_blueprint.route("/changelog")
def changelog():
    city_form = CityForm(request.form)
    return render_template("changelog.html",
                           city_form=city_form)

app/map/routes.py
from flask import Blueprint, render_template, request
from requests import get
from app.forms import CityForm

map_blueprint = Blueprint('map_blueprint',
                          __name__,
                          static_folder='static/map',
                          template_folder='templates')


@map_blueprint.route("/")
def map():
    city_form = CityForm(request.form)

    return render_template("map.html",
                           city_form=city_form)


@map_blueprint.route("/click")
def map_click():
    location_lat = request.args.get("lat")
    location_lon = request.args.get("lon")

    from application import application
    opwm_cel_json = get(f"https://api.openweathermap.org/data/2.5/weather"
                        f"?lat={location_lat}"
                        f"&lon={location_lon}"
                        f"&appid={application.config['OPWM_API_KEY']}"
                        f"&units=metric")\
                            .json()

    return opwm_cel_json

app/weather/routes.py
from flask import Blueprint, render_template, request
from requests import get
from app.forms import CityForm

from app.weather.functions import call_apis, store_data_from

weather_blueprint = Blueprint(
    "weather_blueprint",
    __name__,
    static_folder="static/weather",
    template_folder="templates",
)

locations_counter = []
user_recent_locations_data = []


@weather_blueprint.route("/", methods=["GET", "POST"])
def home():
    city_form = CityForm(request.form)

    # Handling POST request when CityForm is submitted
    if request.method == "POST":
        corrected_user_query_location = city_form.location.data.replace(" ", "%20")
        nominatim_api = get(
            f"https://nominatim.openstreetmap.org/search/"
            f"{corrected_user_query_location}?format=json"
        ).json()
        location_lat = nominatim_api[0]["lat"]
        location_lon = nominatim_api[0]["lon"]

        apis_responses = call_apis(location_lat, location_lon)

        apis_data = store_data_from(
            apis_responses["opwm_cel_api"],
            apis_responses["opwm_fah_api"],
            apis_responses["opwm_cel_forecast_api"],
            apis_responses["opwm_fah_forecast_api"],
            apis_responses["opwm_uv_index_api"],
            apis_responses["timezonedb_api"],
            apis_responses["air_quality_api"],
        )

        locations_counter.append(city_form.location.data.split(",")[0].title())
        locations_counter.reverse()

        user_recent_locations_data.append(
            [
                city_form.location.data.split(",")[0].title(),
                apis_data["country_code"],
                apis_data["weather_cel_temp_current"],
                apis_data["weather_cel_icon_current"],
                apis_data["weather_description"],
            ]
        )
        user_recent_locations_data.reverse()

        city_form.location.data = ""

        return render_template(
            "dashboard.html",
            location_lat=location_lat,
            location_lon=location_lon,
            apis_data=apis_data,
            city_form=city_form,
        )

    # Handling GET request when the 'location' parameter is used in the URL
    elif request.method == "GET" and request.args.get("location"):
        corrected_user_query_location = request.args.get("location").replace(" ", "%20")
        nominatim_api = get(
            f"https://nominatim.openstreetmap.org/search/"
            f"{corrected_user_query_location}?format=json"
        ).json()
        location_lat = nominatim_api[0]["lat"]
        location_lon = nominatim_api[0]["lon"]

        apis_responses = call_apis(location_lat, location_lon)

        apis_data = store_data_from(
            apis_responses["opwm_cel_api"],
            apis_responses["opwm_fah_api"],
            apis_responses["opwm_cel_forecast_api"],
            apis_responses["opwm_fah_forecast_api"],
            apis_responses["opwm_uv_index_api"],
            apis_responses["timezonedb_api"],
            apis_responses["air_quality_api"],
        )

        locations_counter.append(request.args.get("location"))
        locations_counter.reverse()

        user_recent_locations_data.append(
            [
                request.args.get("location"),
                apis_data["country_code"],
                apis_data["weather_cel_temp_current"],
                apis_data["weather_cel_icon_current"],
                apis_data["weather_description"],
            ]
        )
        user_recent_locations_data.reverse()

        city_form.location.data = ""

        return render_template(
            "dashboard.html",
            location_lat=location_lat,
            location_lon=location_lon,
            apis_data=apis_data,
            city_form=city_form,
        )

    # Handling GET request with no parameter
    return render_template("home.html", city_form=city_form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dark-mode.css') }}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet"href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500&family=Jua&display=swap">
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
        <link rel="stylesheet" href="https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='icons/favicon.ico') }}">
        <link rel="apple-touch-icon" href="{{ url_for('static', filename='icons/apple-touch-icon.png') }}" />
        <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='icons/apple-touch-icon-57x57.png') }}" />
        <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='icons/apple-touch-icon-72x72.png') }}" />
        <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='icons/apple-touch-icon-76x76.png') }}" />
        <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='icons/apple-touch-icon-114x114.png') }}" />
        <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='icons/apple-touch-icon-120x120.png') }}" />
        <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='icons/apple-touch-icon-144x144.png') }}" />
        <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='icons/apple-touch-icon-152x152.png') }}" />
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='icons/apple-touch-icon-180x180.png') }}" />
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>
        <script src="https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js"></script>
    </head>
    <body>
        <div class="custom-control custom-checkbox m-4 float-right">
            <input type="checkbox" class="custom-control-input" id="darkSwitch" />
            <label class="custom-control-label no-select" for="darkSwitch">🌙</label>
        </div>
        <div class="main-section container p-4 w-75">
            {% block content %}
            {% endblock %}
        </div>
        {% block footer %}
        {% endblock %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/typeahead/typeahead.bundle.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/typeahead/typeahead_search_bar.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/dark-mode-switch.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/base.js') }}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

app/templates/footer.html
<div class="footer">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12 no-select mt-3">
        <span class="mr-3"><a href="{{ url_for('map_blueprint.map') }}">Map mode</a></span>
        <span class="mr-3"><a href="https://github.com/John35961/weather-app" target="_blank">Fork on GitHub</a></span>
        <span class="mr-3"><a href="mailto:jean.guillet1@gmail.com?subject=Howdy!" target="_blank">Contact</a></span>
        <span class="mr-3"><a href="{{ url_for('about_blueprint.about') }}">About</a></span>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-12 no-select mb-3 text-secondary">
        <span class="mr-3">Made with ♥ in France</span>
      </div>
    </div>
  </div>
</div>

app/templates/header.html
<div class="col-md-8 mb-3">
    <h4><a class="links text-lowercase home-title no-select" href="{{ url_for('weather_blueprint.home') }}">yaws</a></h4>
</div>
<div class="col-md-4">
    <form action="{{ url_for('weather_blueprint.home') }}" method="POST">
        <div class="input-group mb-3">
            {{ city_form.location(class_="search-bar tt-query form-control form-control", placeholder="Enter a location") }}
            <div class="input-group-append">
                {{ city_form.submit(class_="btn btn-sm btn-outline-primary float-right") }}
            </div>
        </div>
    </form>
</div>